### ISSUE TITLE
Test Edge Probing on version-2 annotation trained on different corpora sets with different BERTs

### ISSUE THREAD

**Issue by PolinaZulik** [PolinaZulik/metaphor-psycho#15]
test set - 2,686 examples, majority labelling: 145 met (5.4%), 2,541 non-met (94.6%).

**Comment by PolinaZulik** [comment]
Metaphoric class:
Model|Annotator|Metaphor N, %|Train Corpus|precision|recall|f1-score
--|--|--|--|--|--|--
DeepPavlov/rubert-base-cased-conversational, prop. cased|majority|145, 5.4|lcc+yulia|0.15|0.44|0.23
DeepPavlov/rubert-base-cased-conversational, prop. cased|majority|145, 5.4|lcc+yulia+wiktionary|0.18|0.43|0.25
xlm-roberta-base|majority|145, 5.4|lcc+yulia|0.14|0.34|0.20
xlm-roberta-base|majority|145, 5.4|lcc+yulia+wiktionary|0.16|0.30|0.21
DeepPavlov/rubert-base-cased-conversational, prop. cased|majority|145, 5.4|lcc|0.18|0.27|0.21
DeepPavlov/rubert-base-cased-conversational, prop. cased|majority|145, 5.4|yulia|0.07|0.81|0.13
DeepPavlov/rubert-base-cased-conversational, prop. cased|majority|145, 5.4|wiktionary|0.09|0.59|0.16
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|majority|145, 5.4|lcc+yulia+wiktionary|0.18|0.46|0.25
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = min 1 met annotation|236, 8.8|lcc+yulia+wiktionary|0.28|0.42|0.34
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = min 1 met annotation|236, 8.8|lcc+yulia|0.24|0.47|0.32

**Comment by PolinaZulik** [comment]
**TODO**:

- [x] train and test on the train/dev/test of _rusidiolect_, but use [oversampling](https://imbalanced-learn.org/stable/over_sampling.html) of the met class in train and dev? + group by text ids?

**Comment by PolinaZulik** [comment]
with rusidio met = minimum 1 metaphor annotation, [split](https://colab.research.google.com/drive/14JEpArY4MxGIRcIb4CeJZbZqrN61EbPn#scrollTo=dzrwo4gaKAxx&line=4&uniqifier=1) into train (40%), dev (20%) and test (40%) with filename-groups and met-class stratification:
Model|Annotator|Train Corpus|Test Corpus|P-Met|R-Met|F1-Met|F1-Macro
--|--|--|--|--|--|--|--
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = min 1 met annotation|rusidio-train|rusidio-test|0.72|0.46|0.56|0.76
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = min 1 met annotation|lcc, yulia, rusidio-train|rusidio-test|0.40|0.35|0.38|0.66
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = min 1 met annotation|lcc, yulia, wiktionary, rusidio-train|rusidio-test|0.45|0.27|0.33|0.64
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|rusidio-train|rusidio-test|0.79|0.48|0.60|0.79
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc, yulia, rusidio-train|rusidio-test|0.33|0.23|0.27|0.62
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc, rusidio-train|rusidio-test|0.35|0.21|0.27|0.62

if trained on rusidio only, the result is high.

- [x] if we want to train on rusidio + other corpora, we probably need to oversample rusidio's metaphor class in the train and dev sets. 
- [x] make grouping by respondent id, not text id!
- [x] we should try the same rusidio-only experiment with majority annotation and respective split stratification.

**Comment by PolinaZulik** [comment]
RusIdio **oversampled** to 50/50 by **majority annotated metaphor labels**:

Model|Annotator|Train Corpus|Test Corpus|P-Met|R-Met|F1-Met|F1-Macro
--|--|--|--|--|--|--|--
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|rusidio-train|rusidio-test|0.30|0.78|0.43|0.68
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc+yulia, rusidio-train|rusidio-test|0.20|0.85|0.32|0.60
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc+yulia+wiktionary, rusidio-train|rusidio-test|0.20|0.83|0.32|0.60
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc, rusidio-train|rusidio-test|0.20|0.88|0.32|0.60
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|yulia, rusidio-train|rusidio-test|0.21|0.83|0.34|0.62
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|wiktionary, rusidio-train|rusidio-test|0.21|0.81|0.33|0.61

RusIdio **oversampled** to 50/50 by **min1-met annotated metaphor labels**:

Model|Annotator|Train Corpus|Test Corpus|P-Met|R-Met|F1-Met|F1-Macro
--|--|--|--|--|--|--|--
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = min1-met annotation|rusidio-train|rusidio-test|0.31|0.77|0.44|0.67
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = min1-met annotation|lcc+yulia, rusidio-train|rusidio-test|0.21|0.81|0.33|0.58

**Comment by PolinaZulik** [comment]
oversampling reduces results.
try oversampling with 1/4 proportion?

**Comment by PolinaZulik** [comment]
RusIdio **oversampled** to 20/80 by **majority annotated metaphor labels**:

Model|Annotator|Train Corpus|Test Corpus|P-Met|R-Met|F1-Met|F1-Macro
--|--|--|--|--|--|--|--
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|rusidio-train|rusidio-test|0.64|0.54|0.59|0.78
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc+yulia, rusidio-train|rusidio-test|0.38|0.39|0.39|0.68

**Comment by PolinaZulik** [comment]
RusIdio **oversampled** to 25/75 by **majority annotated metaphor labels**:

Model|Annotator|Train Corpus|Test Corpus|P-Met|R-Met|F1-Met|F1-Macro
--|--|--|--|--|--|--|--
**NB** DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|rusidio-train|rusidio-test|0.56|0.59|**0.57**|**0.77**
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc+yulia, rusidio-train|rusidio-test|0.39|0.47|0.43|0.70
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc+yulia+wiktionary, rusidio-train|rusidio-test|0.45|0.44|0.44|0.71
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc, rusidio-train|rusidio-test|0.40|0.39|0.39|0.68
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|yulia, rusidio-train|rusidio-test|0.45|0.47|0.46|0.72
**NB** DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|wiktionary, rusidio-train|rusidio-test|0.53|0.53|**0.53**|**0.75**
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc+wiktionary, rusidio-train|rusidio-test|0.57|0.39|0.46|0.72
**NB** DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|yulia+wiktionary, rusidio-train|rusidio-test|0.51|0.58|**0.54**|**0.76**
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|yulia+wiktionary|rusidio-test|0.09|0.68|0.16|0.44

**Comment by PolinaZulik** [comment]
aye!
ToDo:

- [x] add results for the best combinations with swapped _train_ and _test_ folds in _RusIdio_. the final result should be the mean between the original and the swapped cases.

**Comment by PolinaZulik** [comment]
Same as above, but train-test split reversed in rusidio:

Model|Annotator|Train Corpus|Test Corpus|P-Met|R-Met|F1-Met|F1-Macro
--|--|--|--|--|--|--|--
**NB** DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|rusidio-train|rusidio-test|0.52|0.60|0.56|0.77
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc+yulia, rusidio-train|rusidio-test|0.45|0.40|0.42|0.70
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc+yulia+wiktionary, rusidio-train|rusidio-test|0.45|0.40|0.42|0.70
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc, rusidio-train|rusidio-test|0.49|0.36|0.42|0.69
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|yulia, rusidio-train|rusidio-test|0.42|0.47|0.44|0.70
**NB** DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|wiktionary, rusidio-train|rusidio-test|0.62|0.36|0.46|0.72
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|lcc+wiktionary, rusidio-train|rusidio-test|0.45|0.31|0.37|0.67
**NB** DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|yulia+wiktionary, rusidio-train|rusidio-test|0.39|0.45|0.42|0.69
DeepPavlov/rubert-base-cased-conversational, **not** prop. cased|met = majority annotation|yulia+wiktionary|rusidio-test|0.09|0.67|0.15|0.45

**Comment by PolinaZulik** [comment]
majority annotation.
3-fold cv, 1/2 train, 1/6 dev, 1/3 test; stratified by majority annotation groups by person.
DeepPavlov/rubert-base-cased-conversational, not prop. cased.

split-1:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/2161303/192540471-65ec9632-0361-401f-80ef-2fcbf90c0b8c.png">

split-2:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/2161303/192541793-8ba60e9d-ed36-4c30-b11b-bdccf46a6b67.png">

split-3:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/2161303/192542666-a23556a3-ff4f-437f-8245-61e462b12610.png">

**Comment by PolinaZulik** [comment]
Metaphor class, mean over splits: 
P = 0.783 +- 0.009
R = 0.460 +- 0.082
F1 = 0.577 +- 0.069

F1-macro = 0.780 +- 0.033

**Comment by PolinaZulik** [comment]
correlations on 100 docs: https://docs.google.com/spreadsheets/d/1H592ue2psZyPeREIjra6AnjPsYB1lWVJ-UpSegtrqXE/edit#gid=1696541437 .

all p-values > 0.1. gonna try on the whole large doc collection.

**Comment by PolinaZulik** [comment]
large doc collection (933 docs): https://docs.google.com/spreadsheets/d/1BGiyYKzn76hm0XqyBnie2V0XK4ykLXOgczoQbK2x8sQ/edit#gid=1916703286

**Comment by PolinaZulik** [comment]
first experiments again:

Model|Annotator|Metaphor N, %|Train Corpus|precision|recall|f1-score|f1-macro
--|--|--|--|--|--|--|--
DeepPavlov/rubert-base-cased-conversational, not prop. cased|majority|145, 5.4|lcc|0.17|0.28|0.21|0.57
DeepPavlov/rubert-base-cased-conversational, not prop. cased|majority|145, 5.4|yulia|0.07|0.71|0.13|0.35
DeepPavlov/rubert-base-cased-conversational, not prop. cased|majority|145, 5.4|wiktionary|0.08|0.54|0.13|0.44
DeepPavlov/rubert-base-cased-conversational, not prop. cased|majority|145, 5.4|yulia+wiktionary|0.08|0.64|0.15|0.44
DeepPavlov/rubert-base-cased-conversational, not prop. cased|majority|145, 5.4|lcc+wiktionary|0.17|0.37|0.23|0.58
DeepPavlov/rubert-base-cased-conversational, not prop. cased|majority|145, 5.4|lcc+yulia|0.15|0.47|0.23|0.56
DeepPavlov/rubert-base-cased-conversational, not prop. cased|majority|145, 5.4|lcc+yulia+wiktionary|0.18|0.44|0.26|0.59
